{% set name = "perl-array-shuffle" %}
{% set version = "0.03" %}
{% set sha256 = "bd0fcb784e9ca1a8be1627bde1d0c0ae321b71382525484a688073246be77450" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SA/SALVA/Array-Shuffle-0.03.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - perl
    - perl-extutils-makemaker

  run:
    - perl

test:
  imports:
    - Array::Shuffle

about:
  home: http://metacpan.org/pod/Array::Shuffle
  license: perl_5
  summary: 'fast shuffling of arrays in-place'
