{% set name = "metapi" %}
{% set version = "0.9.3" %}
{% set sha256 = "daaa59b5a3a2f2cba33e9ee784b9fa4305d3f53382b45743b60348f9e4fb3326" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ohmeta/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - metapi = metapi.corer:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - openpyxl
    - biopython
    - ruamel.yaml
    - snakemake
    - insilicoseq
    - fastqc
    - seqtk 
    - seqkit
    - multiqc
    - pigz
    - fastp
    - sickle-trim
    - bwa
    - bowtie2
    - samtools
    - sambamba
    - megahit
    - idba
    - spades
    - maxbin2
    - concoct
    - metabat2
    - das_tool
    - prokka
    - kraken2
    - bracken
    - gtdbtk

test:
  imports:
    - metapi
  commands:
    - metapi --version
    - metapi init --help
    - metapi denovo_wf --help

about:
  home: https://github.com/ohmeta/metapi
  summary: 'metapi is a pipeline to construct a genome catalogue from metagenomics data'
  license: GPL3
  license_family: GPL

extra:
  identifiers:
    - biotools:metapi
  recipe-maintainers:
    - alienzj
