{% set version = "1.1.2" %}

package:
  name: ushuffle
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/b/ushuffle/ushuffle-{{ version }}.tar.gz
  sha256: "bd2c1d038a6d67d5a0c9f3e0b1761dccd9400bde666c82bb8f44732b72d417b6"

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python
    - cython >= 0.27.1
    - pip
  run:
    - python

test:
  imports:
    - ushuffle

about:
  home: https://github.com/guma44/ushuffle
  license: BSD
  license_family: BSD
  summary: "A Cython wrapper over uShuffle - a useful tool for shuffling biological sequences while preserving the k-let counts"
  doc_url: 'https://cs.usu.edu/people/MinghuiJiang/ushuffle/'

extra:
  recipe-maintainers:
    - guma44
